spring.application.name=lshw-server
spring.output.ansi.enabled=ALWAYS
pring.banner.location=classpath:banner.txt
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} %clr([%thread]){magenta} %clr(%-5level){red} %clr(%logger{36}){cyan} - %msg%n
